# Site settings
title: Bistro Digital
email: francisco@bistro.digital
description: > # this means to ignore newlines until "baseurl:"
  Software agency with great taste for code. iOS, Android and Web application development. Build your next app with us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bistro.digital" # the base hostname & protocol for your site

# User setting
owner: Francisco Granados
email: francisco@bistro.digital
facebook_username: gzfrancisco
twitter_username: gzfrancisco
github_username: BistroDigital
address:
  - line: Cocoteros 195, Azcapotzalco
  - line: Mexico city
  # Feel free to add more lines here
telephone: +52 1 55 5214 4361
copyright: Bistro Digital

# API settings
google_api_key: AIzaSyBAOalaUiIv4qm9TQbfRUhsiaDpTNfZ8C0

# Build settings
markdown: kramdown
