# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bistro Digital [software cuisine]
email: francisco@bistro.digital
description: > # this means to ignore newlines until "baseurl:"
  Software agency with power developers/cheffs.
  We programming ingredients and serve hot in your device.
url: "http://bistro.digital" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  bistrodigital
permalink: pretty

# Build settings
markdown: kramdown
