# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bistro Digital
email: francisco@bistro.digital
description: > # this means to ignore newlines until "baseurl:"
  Bistro Digital is a software consulting team, focused in product development. The team is high skilled in
  many technologies like iOS, Android, HTML5+CSS3+Javascript, Ruby, Java, PHP and many others. We use our unique
  software development methodology based in the SCRUM framework and the manifesto for agile software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bistro.digital" # the base hostname & protocol for your site
twitter_username: BistroDigital
github_username:  BistroDigital

# Build settings
markdown: kramdown
